---
# =============================================================================
# DOCKER ROLE - Default Variables
# =============================================================================

docker_edition: "ce"
docker_users: []
