---
# roles/agent/handlers/main.yml

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart zt-agent
  systemd:
    name: zt-agent
    state: restarted

- name: restart wireguard
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    state: restarted
